### ISSUE TITLE
Ejecución de shots mediante <repoType>:<optional>:<shot>

### ISSUE THREAD

**Issue by sbonacho** [cellsjs/piscosour#12]
Ejecutar shot al estilo cells

cells component:validate:lint o cells component::lint en lugar de con -s

**Comment by sbonacho** [comment]
no se va a hacer. 

El usuario siempre tiene que ejecutar straws, si queremos que ejecute un solo shot tendremos que hacer un straw con un shot.

**Comment by biaggi** [comment]
Si no te importa y si nadie tiene nada en contra, lo haré yo cuando tenga tiempo.

Creo que es algo útil y nos ahorra tiempo

**Comment by sbonacho** [comment]
No me importa hacerlo, pero quedamos en la reunión del otro día que lo haríamos de la otra manera por eso lo he cerrado. Si quieres hacerlo tu, adelante ;)

**Comment by biaggi** [comment]
No recuerdo esa decisión así, sinceramente, genera overhead a la hora de crear recetas, hay un ejemplo al menos en el que tendría sentido:

El hook que tienen los programadores instalado, es algo que unas veces quieren llamar por separado y que producto quiere que se llame entero antes de cada push.

Ahí tendría sentido. Sigues pensando que habría que cerrar la issue?

**Comment by sbonacho** [comment]
No, a mi me parece bien que se puedan llamar a shots directamente ;).

**Comment by sbonacho** [comment]
Now is posible to execute shots using <repoType>:<straw>:<shot> featured in #45
