### ISSUE TITLE
eliminar fs.existsSync

### ISSUE THREAD

**Issue by sbonacho** [cellsjs/piscosour#13]
eliminar las llamadas a fs.existsSync cambiarlas por fs.stat

**Comment by biaggi** [comment]
Porqué has marcado la issue como wontfix? existSync está deprecated

https://nodejs.org/api/fs.html#fs_fs_existssync_path

Desaparecerá en algún momento, pienso que es mejor cambiarlo ahora que hacerlo cuando haya desaparecido.

**Comment by sbonacho** [comment]
ha sido ignorancia... ;). ¿Cual sería la etiqueta correcta?

**Comment by sbonacho** [comment]
Fix with #48
