### ISSUE TITLE
Mensaje predeterminado de pisco personalizable

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#15]
Actualmente tengo integrado el comando cellsjs con pisco, sin embargo, cuando se ejecuta el parámetro sin comandos, la ayuda que aparece es la de pisco y no es lo deseable, desde mi punto de vista, lo deseable es que la ayuda que aparece ahí sea de alguna forma customizable por el desarrollador.

Hay alguna forma actualmente de hacer esto?

**Comment by sbonacho** [comment]
Estoy trabajando en que la ayuda, para que lo que aparezca sea un poco más
concreto y muestre los comandos concretos que se pueden ejecutar. es decir:

Listado de todas las repoType:straws disponibles y todos los
repoType::shots disponibles...

por ejemplo

straw
cells component:validate

shots
cells component::lint
cells component::demo-validate
cells component::s3

espera a ver si mañana lo tengo listo y te lo enseño...

una posible mejora sería que en configuración (piscosour.json) se pudiera
filtrar los comandos que se quiere que aparezcan en la ayuda.

**Comment by sbonacho** [comment]
por cierto el shot de s3 lo tengo hecho en pisco-cells en stash Cells labs

El 16 de febrero de 2016, 17:16, Santiago García-Bonacho <sbonacho@gmail.com

**Comment by biaggi** [comment]
Prefiero que la ayuda que se muestra sea algo personalizado, sinceramente, no quiero que quien use el comando tenga la necesidad de saber qué es una receta, un straw o un shot.

En cualquier caso, para mi, no es prioritario

**Comment by biaggi** [comment]
Con respecto al s3, prefiero implementar uno propio, es copiar/pegar código de otro sitio y ya está integrado con lo que tengo que hacer.

**Comment by sbonacho** [comment]
Solucionado con #35
