### ISSUE TITLE
Volviendo al tema del pisco.js de bin

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#2]
No tiene ningún sentido, puedes usar el de node_modules/piscosour/bin/pisco.js o incluso instalar pisco de forma global y usar el de `npm get prefix`/lib/node_modules/piscosour/bin/pisco.js.

No verás que gulp te añada ningún gulp.js en tu proyecto.

Cuando termine la parte de cellsjs, haré un pr para que veas un ejemplo

**Comment by biaggi** [comment]
Vale, ya he entendido el problema, pisco.js debe estar en la receta para poder estimar la ruta de la receta, aún así no debería haber código dentro de las recetas específico de pisco, esta es mi propuesta:

```
diff --git a/bin/pisco_ b/bin/pisco_
index 78a5f2e..f6e0c51 100755
--- a/bin/pisco_
+++ b/bin/pisco_
@@ -1,12 +1,2 @@
 #!/usr/bin/env node
-var sour = require("piscosour").Sour();
-
-var onFulfilled = function () {
-    process.exit(0);
-}
-
-var onRejected = function (err) {
-    process.exit(-1);
-}
-
-sour.gush().then(onFulfilled, onRejected);
\ No newline at end of file
+require("piscosour").init();
\ No newline at end of file
diff --git a/index.js b/index.js
index e7291cb..475f136 100755
--- a/index.js
+++ b/index.js
@@ -18,7 +18,17 @@ var Piscosour = {
     fsUtils: fsUtils,
     logger: logger,
     config: config,
-    params: params
+    params: params,
+    init: function() {
+        var sour = require("piscosour").Sour();
+        sour.gush().then(function () {
+            process.exit(0);
+        }, function () {
+            process.exit(-1);
+        });    
+    }
+
 };

+
 module.exports = Piscosour;
\ No newline at end of file

```

**Comment by sbonacho** [comment]
Me parece bien la mejora... mejor una línea que 5 ;), si no te parece mal, voy a usar tu fichero diff pero cambiando unas tonterías.. quedaría así:

-- template/bin/_pisco

#!/usr/bin/env node
require("piscosour").gush();

-- bin/pisco.js

#!/usr/bin/env node
require("..").gush();

-- index.js

var Piscosour = {
    Shot: Shot,
    Sour: Sour,
    fsUtils: fsUtils,
    logger: logger,
    config: config,
    params: params,
    gush: function () {
        this.Sour().gush().then(this.onFulfilled, this.onReject);
    },
    onFulfilled : function(){
        process.exit(0);
    },
    onReject : function(){
        process.exit(-1);
    }
};

**Comment by sbonacho** [comment]
subido en la versión 0.0.16
