### ISSUE TITLE
bin/cmd necesita u+x

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#20]
El archivo bin que se crea, debería tener permisos de ejecución

~/cells/cells-pisco-application-deploy$ ls -la bin/pisco.js 
-rw-rw-r-- 1 jmgomez jmgomez 48 feb 18 10:42 bin/pisco.js

**Comment by sbonacho** [comment]
no consigo reproducir la configuración de permisos. Tanto si hago un git clone como si hago un npm install como si hago un pisco create...

**Comment by biaggi** [comment]
Lo siento, tendría que haber especificado la versión o ejemplo de código.

Por cierto dónde está alojado el generador que estás usando? veo que se llama generator-pisco-recipe, pero no lo veo ni en stash ni en github, he visto que hay uno en tu cuenta, pero no tiene cambios desde hace tiempo.

**Comment by sbonacho** [comment]
Es el de github que está en mi cuenta.. sí, hace tiempo que no lo toco.

**Comment by biaggi** [comment]
Vale, entonces debe ser por que yo hago algo fuera de lo común al hacer la instalación por que ese repo no se toca desde hace tiempo. Si vuelve a suceder intentaré documentar mejor bajo qué circunstancias sucede.

Estaría bien también mover el repo del generador a cells
