### ISSUE TITLE
Añadir al logger los métodos necesarios para que se puedan pasar instancias de ese logger y puedan ser usadas de forma transparente en otras partes

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#21]
Por alguna extraña razón, el logger de pisco colisiona con el logger de cells-ci-applications-deploy (que es un bunyan), la solución más razonable, es pasar el shot.logger a mi objeto para que, en caso de ser recibido, pueda usarlo en lugar del bunyan que uso.

Que haya detectado falta el método debug, no se si alguno más, lo añadiría yo, pero no se qué logLevel le quieres asignar a ese tipo de trazas.

Saludos

**Comment by sbonacho** [comment]
Completamente de acuerdo!

**Comment by biaggi** [comment]
Lo voy a implementar de otra forma, ya no es necesario
