### ISSUE TITLE
Añadir una biblioteca común para varios pasos

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#23]
En mi script tengo la necesidad de añadir una parte de código que comparten varios pasos (una biblioteca), no es un paso en si, me podrías indicar cual es la forma correcta de hacer esto?

**Comment by sbonacho** [comment]
Perdona que no he contestado... hora extraña de contestar, pero como esto
me llega a mi correo personal, lo he visto y ahí va ;)

La mejor manera es: importar la librería en los dos shot y hacer las
llamadas que necesites en los dos shots en el contexto de una receta. Es
decir.

recipeRoot/lib/libreria.js
               /shots/<nombre>/<repoType>/shot.js
               /shots/<nombre2>/<repoType>/shot.js

dentro de los dos shot.js

var libreria = require('../../../lib/libreria');

libreria.algo();

algo así...

**Comment by biaggi** [comment]
Ok, eso es lo que estaba haciendo
