### ISSUE TITLE
Paso de parámetros entre pasos

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#25]
Actualmente y si he entendido bien sólo existe un método de comunicación entre pasos:

shot.set(key, value);
shot.get(key, step)

Esto me obliga a acoplar fuertemente pasos y a convertirlos en no reutilizables.
Hay alguna otra forma de pasar parámetros a pasos que no sea explicitando el origen?

Saludos

**Comment by sbonacho** [comment]
Solucionado actualmente en esta rama que espero mergear hoy https://github.com/cellsjs/piscosour/tree/fix/some_bug_fix

**Comment by sbonacho** [comment]
Corregido en pull request #35
