### ISSUE TITLE
Organización de recipeType, straw y shot más natural

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#27]
No termino de entender el por qué de esta organización de carpetas, me resultaría más natural algo así:

recipeType
 |--------------strawFolder
 ---------------|--------------straw.json
 ---------------|--------------shotFolder
 --------------- ---------------|---------------shot1
 --------------- ---------------|---------------shot2
 --------------- ---------------|---------------shot3

**Comment by sbonacho** [comment]
Un shot puede estar en varios straws por esa razón tienen que estar en carpetas separadas. De otra manera habría que duplicar código.

También puede haber straws que se puedan ejecutar en dos tipos de repositorio. Por lo tanto no se puede asociar un straw a un tipo de repositorio.

Por ejemplo, supongamos el straw "validate" compuesto por los shots "check-out" "build" "test" "deployment"

tendremos: 

[recipeRoot]/straws/validate/straw.json

``` js
{
  "params" : {},
  "shots" : {
    "check-out" : {},
    "build" : {},
    "test" : {},
    "deployment" : {}
  }
}
```

Podemos implementar este straw para un tipo de repositorio llamado "component" tendremos esta estructura:

[recipeRoot]/shots/check-out/component
----------------|-------/build/component
----------------|-------/test/component
----------------|-------/deployment/component

Pero también podemos implementar este straw para un tipo de repositorio llamado "app" y tendremos esta estructura

[recipeRoot]/shots/check-out/app
----------------|-------/build/app
----------------|-------/test/app
----------------|-------/deployment/app

Pero también podríamos tener otro straw llamado "deploy" que solo tenga dos shots "build" y "deployment" para los dos tipo de repositorio "component" y "app" 

[recipeRoot]/straws/deploy/straw.json

``` js
{
  "params" : {},
  "shots" : {
    "build" : {},
    "deployment" : {}
  }
}
```

**Comment by biaggi** [comment]
Ok, entiendo tu explicación. 

A mi lo que me suena mal, es que dentro de shot haya una carpeta que indica a que repository type pertenece. Un shot como por ejemplo un git clone, un move o un copy, pueden pertenecer tanto a un componente como a una aplicación, en ese caso también estaríamos duplicando código.

Por qué no aplanamos toda la estructura y de esa forma todo es completamente reutilizable?

Me refiero a tener una carpeta shots, una straws y una recipes.

**Comment by sbonacho** [comment]
Para eso existe la carpeta default. Cuando el código de un shot aplica a cualquier tipo de repositorio este tiene que ir dentro de la carpeta default. Actualmente esto no está funcionando, funcionará después de la refactorización.

recipeRoot/shots/check-out/default <- Este será llamado sea cual sea el tipo de repositorio

La verdad es que yo también le estaba dando vueltas a lo mismo ;). Y sí, tienes razón acoplar todo esto a una estructura de directorios por un lado no me gusta. Estoy pensando en meter propiedades a los shots donde se establezca en que tipo de repositorio actúa y así nos quitaríamos la dependencia a las carpetas, por lo menos en lo que refiere a tipo de repositorio. 

Por otro lado me gusta que cada shot resida en una carpeta, más que nada para que contenga todos los ficheros que componen ese shot (params.json, info.md, shot.js... y si surgen más pues más... se me ocurre tests.js... )

**Comment by biaggi** [comment]
Menos es más, quiero decir más que meter la carpeta default, tiene más sentido directamente quitar la carpeta repositotyType de dentro de los shots. 

Implicaciones:

pluses: total reutilización de código, no necesitas realmente especificar repotype para los shots
contras: no puedes tener un shot con el mismo nombre para dos repotypes

Con respecto a que cada shot resida en una carpeta, totalmente de acuerdo. Pero me gustaría saber qué pasó con eso de que los shots pudieran ser módulos externos y que la receta contuviera sólo la configuración particular. Eso si que haría todo el sistema totalmente reutilizable.

**Comment by sbonacho** [comment]
Buenas!

Una de las filosofías y de los objetivos de piscosour es el de organizar y
estructurar de una manera humana los scripts que tenemos por ahí. Es
importante entender esta filosofía, la idea no es hacer tareas de bajo
nivel destinadas a ser reutilizadas, la idea es organizar el conocimiento y
organizar los scripts de una manera lógica para poder planificar procesos
más complejos sean de integración continua, pruebas, instalaciones o
aprovisionamiento de entornos. Piscosour no es una herramienta de
construcción tipo gulp, grunt, geoman (ant, gradle, maven) es más bien un
planificador distribuido tipo jenkins, bamboo, gocd...

Javascript tiene el problema de que es muy sencillo y muy versatil, y las
líneas que separan las distintas funcionalidades muchas veces son muy
finas, pero tenemos que tener claro cual es nuestra filosofía y que nos
interesa más dar prioridad.

Para mi la reutilización es importante, y piscosour la permite, pero creo
que hay límites, fronteras...  *creo que es bueno hacer shots específicos
para cada tipo de repositorio y si queremos reutilizar pare de nuestro
código lo haría en librerías externas usadas por cada uno de los shots. *

Con la introducción de los plugins, actualmente en el backlog, se va a
introducir un método de reutilización y ampliación de funcionalidad del
core. _Creo que en los plugins si está la respuesta a la reutilización_.

Espero que haya servido de ayuda ;)
Muchas gracias!!

**Comment by biaggi** [comment]
Me parece bien esa filosofía, pero lo cortés no quita lo valiente, quiero decir, que la filosofía sea organizar scripts de manera lógica para planificar procesos, es el qué. Lo que yo propongo es un detalle que afecta al cómo se hace.

Opino que si un componente es reutilizado en varios puntos sin tener que hacer copy&paste, la cantidad de errores va a ser menor que si detecto un error en un punto y tengo que ir receta por receta a ver dónde está siendo utilizado.

La implementación de esta solución además es bastante sencilla, simplemente es cuestión de hacer un require del shot y node se encargará de buscarlo allá donde esté y si no lo encuentra, como fallback se puede usar la estructura actual de carpetas, los shots que no están en carpetas, obviamente serían dependencias en el package.json. Igual hasta se puede portar ese código a un resolver de npm para así podernos abstraer totalmente de esta estructura de carpetas.

Los archivos de configuración por otra parte, son específicos de la receta y desde mi punto de vista, no reutilizables, aunque no descarto que los shots contengan algún default configuration.

Hay un dicho muy interesante que aplica en estos casos: fall in love with the problem, not with the solution. Esto te permite probar cosas diferentes

**Comment by sbonacho** [comment]
estoy de acuerdo, manteniendo la filosofía podemos cambiar el cómo, en mi comentario número 5 de este issue hablo de que en un futuro se podrá eliminar la carpeta del tipo de repositorio metiendo esta información como un atributo dentro del shot, pero eso no significa que perdamos esa información , los shots siguen estando asociados a un tipo de repositorio. Si queremos hacer un shot que aplique a todos los tipos de repositorio será de tipo "default". 

en cuanto a la configuración, la idea es que el programador de shots declare las parámetros que necesite y se olvide de donde provienen, como indico en este articulo:

https://github.com/cellsjs/piscosour/blob/feature/documentation/doc/Load_Parameters.md

la configuración no es única en la receta, la configuración se aplica a varios niveles
- shot
- straw
- receta
- repositorio  

Y su introducción comprende estos métodos:
- Variables de entorno
- Parámetros por línea de comando
- Fichero de configuración
- Preguntas al usuario usando inquirer 

En cuanto a la frase que pones, estoy completamente de acuerdo ... ;)

**Comment by biaggi** [comment]
No critico la parte de configuración, eso estoy de acuerdo que pertenece a la receta y obviamente la configuración concreta y final debe estar en la receta, la herencia de configuración también me parece bien.

La cuestión es que yo pienso que un shot per se es una tarea, no debe estar asociado a ningún tipo de repositorio. Es como en css, no se pone como nombre boton_rojo, por que en algún momento ese botón puede ser azul. Aplicado a este caso, establecer que un shot siempre va a aparecer en un tipo de repositorio es un error, ya que hace que no sea reutilizable en otro tipo repositorio por una cuestión de categorización. La solución es duplicar código o refactorizarlo para que sea default, sin embargo, si los shots no están asociados por construcción a un tipo de repositorio sino que lo están por configuración, todo es más reutilizable y no hay que tener en cuenta dónde se va a usar en el momento de su construcción y nos ahorramos la categorización de "default" y preplanificar el uso de una tarea.

Ahora mismo no hay ninguna restricción a nivel de repositorio que impida que esto esté programado así AFAIK

**Comment by sbonacho** [comment]
La idea es que el programador de shots lo haga contextualizado en un caso concreto. Realmente lo que quiero es que la responsabilidad y la funcionalidad de un shot sea pequeña y así hacer más sencillo su manejo. Por supuesto que un shot es un módulo node y como tal se puede importar en cualquier otro lado pero no quiero desvirtuar su valor como entidad que tiene un ciclo de vida y que sirve para orquestar un workflow concreto en un tipo de repositorio concreto.

Para la reutilización de código propongo el concepto de plugin, actualmente en el backlog, un plugin será una entidad nueva que aporte funcionalidad a los shots y que será fácilmente compartida entre varios shots.

Un plugin se declarará en el archivo params.js de un shot y podrá ser accedido a través de shot.plugins('pluginName').run(); (por ejemplo). Este plugin declarará un interfaz y por lo tanto será una inyección en toda regla.  Este plugin podrá compartir funcionalidad y ser usado por varios módulos a la vez. También se podrá cambiar en cualquier momento y si se mantiene su interfaz no afectará a todos los shots que lo usen.

**Comment by biaggi** [comment]
Vale, entonces estamos en desacuerdo en lo fundamental.

Yo como programador de shots, no quiero tener que contextualizar nada si no es estrictamente necesario, no quiero hacer ningún tipo de trabajo dos veces, por que al final me va a requerir más mantenimiento.

El tema de plugins me parece bien, pero no resuelve completamente el problema, son una ayuda para crear un shot, pero sigue estando el tema de que un shot tiene por construcción una restricción artificial que le ata a un repository type por un nombre de carpeta simplemente. Si eso en lugar de ser un nombre de carpeta, fuera una entrada en el params.json todo sería más versatil. 

Es un cambio minúsculo y lo que se gana es mucho.

---

Versión repotype dentro de la carpeta del shot:
Pro:

Contra:
Impide su reutilización en otro repo diferente

---

Versión repotype por configuración:
Pro:
Permite su reutilización en otro repo diferente
Evita duplicidades de código, si soluciono un bug en uno automáticamente se solucionará en todas las instancias de ese shot

Contra:
Realmente sólo estamos cambiando dónde se definie el repoType al que pertenece, la solución es equivalente, así es que los mismos que tenga la opción del repotype como carpeta a excepción obviamente del tema de reutilización.

---

Puedes ampliar esta lista de pros y contras para que lo vea más claro?

**Comment by sbonacho** [comment]
En el comentario número 5 y en el número 9 de este issue comento exactamente lo mismo que acabas de comentar. Por lo tanto estoy **de acuerdo** en que el tipo de repositorio no esté expresado únicamente en la carpeta donde reside y se convierta en una parámetro del shot. Por lo tanto no entiendo tu último comentario... 

Lo que si que quiero es que un shot siga asociado a un tipo de repositorio (incluso creo que debería desaparecer el concepto de default), y lo que no quiero es usar un shot como si fuera una librería más perdiendo su entidad como paso de un workflow con un ciclo de vida dado para un tipo de repositorio dado.

**Comment by biaggi** [comment]
Me puedes explicar cómo cambiando la carpeta por un parámetro de configuración, el shot pierde su entidad de ser un paso con algún ejemplo?, esa implicación para mi no es tan clara.

**Comment by sbonacho** [comment]
Un shot **no pierde su** entidad de ser paso por el hecho de definir el tipo de repositorio al que aplica en su configuración. Es precisamente el mensaje que quiero transmitir.

**Comment by sbonacho** [comment]
con la refactorización #45 se ha incluido la posibilidad de incluir un shot sin especificar el tipo de repositorio al que pertenece. Esto es: es posible crear un shot a este nivel

**[recipeRoot]/shots/[shotName]/shot.js**

Este shot será llamado siempre que no exista un shot.js específico para el tipo de repositorio que del comando que se esté llamando. Esto es, si por ejemplo llamamos a la straw llamada, por ejemplo, **validate** que contiene los pasos: 

check-out, lint, demo, test  

para el tipo de repositorio **component**

la estructura de directorios es la siguiente:

[recipeRoot]/shots/check-out/shot.js
[recipeRoot]/shots/lint/component/shot.js
[recipeRoot]/shots/demo/component/shot.js
[recipeRoot]/shots/test/component/shot.js

pisco llamará a los shots de componente para los pasos lint, demo y test pero llamará al genérico para check-out

De esta manera la especialización de los pasos se puede hacer de varias maneras:
- Usando distintas carpetas
- Capturando el tipo de repositorio que estamos ejecutando y actuando por configuración.
