### ISSUE TITLE
Si dentro de un straw, un shot aparece dos veces, sólo ejecuta la primera

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#28]
Tengo dos ejecuciones de gulp con distintos parámetros, esto impediría la reutilización de código en un mismo straw

Ejemplo: 

https://descinet.bbva.es/stash/scm/cellslabs/cells-pisco-application-deploy.git
rama: feature/two_shots

bin/pisco app:perform

**Comment by sbonacho** [comment]
Con el refactor que se está llevando a cabo de la carga de la configuración inicial estaría solucionado.

**Comment by sbonacho** [comment]
solucionado con #43 

Para incluir dos veces el mismo shot es necesario llamar a los shot de maneras distintas. 

"test:1" el nombre del shot es test detrás del : se puede poner lo que cada uno desee.

``` js
{
  "shots" : {
    "test2" : {},
    "test:1" : {
      "params" :  {
        "execution" :  "PRIMERA"
      }
    },
    "test:2" : {
      "params" :  {
        "execution" :  "SEGUNDA"
      }
    },
    "testint" :{
      "type" : "straw"
    }
  }
}
```

**Comment by sbonacho** [comment]
para probar ejecutar "pisco test"
