### ISSUE TITLE
Me faltan parámetros en la ejecución de un straw

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#29]
Tengo un straw con sus parámetros definidos, no está documentado, pero tenía entendido que los parámetros se mergeaban y el resultado era pasado al shot.

He definido un straw con un par de parámetros y estos no llegan al shot.

Tienes un ejemplo en:

Repositorio:
https://descinet.bbva.es/stash/scm/cellslabs/cells-pisco-application-deploy.git
Rama:
feature/parameters_bug

**Comment by sbonacho** [comment]
Cierto. no se están pasando bien los parámetros definidos en el straw, la verdad no lo había usado hasta ahora ;). Lo corrijo y lo subo. 

Muchas gracias!

**Comment by sbonacho** [comment]
solucionado con #43
