### ISSUE TITLE
Organización de carpetas

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#3]
Tiene sentido que si creamos una receta, esta se cree con la siguiente estructura de carpetas?

(1)cells
(2)|-----cells (código fuente)
(3)|-----test-reports (xml de los test)

Yo preferiría que test-reports estuviera dentro de cells(2), de esta forma, cells(1) no sería necesaria

**Comment by sbonacho** [comment]
Vuelvo a no entender muy bien la pregunta... :)

Cuando se crea una receta ejecutando el comando "pisco create" se crea un directorio con el nombre que le hemos puesto a la receta y dentro se crea la receta completa. El directorio test-reports se escribe al final cada vez que se ejecuta cualquier straw de pisco y contiene el fichero junit.xml con el resultado de la ejecución de todos los shots que contiene el straw. 

pisco create es un straw por lo tanto su ejecución genera este directorio. Propondría, como mejora, que este directorio solo se generará si se le pasa algún parámetro al comando y solo usarlo cuando se ejecute pisco sour dentro de bamboo, por ejemplo.

Creo la mejora...

**Comment by sbonacho** [comment]
pasado a la mejora #11

**Comment by biaggi** [comment]
Efectivamente no veo que hayas entendido la pregunta. Por lo que entiendo de tu respuesta estás tratando la creación o no de la carpeta, cuando mi propuesta va dirigida a dónde se crea esa carpeta.

Ahora mismo al crear una receta, esta crea dos carpetas, la de la receta y la de los test, sin entrar a discutir si la creación de esa carpeta es o no opcional, creo que estaría más organizado si la carpeta de test se crea siempre que corresponda dentro de la receta o en la carpeta que se designe por parámetro de ser necesario.

**Comment by sbonacho** [comment]
jejee tampoco has entendido la respuesta

1) Siempre que se ejecuta un straw se crea una carpeta de resultados de
test independientemente de lo que haga ese straw.
2) La creación de una receta es un straw.
3) Es conveniente que la straw de creación de una receta cree una carpeta
para meter el contenido de la receta.

Si juntas los 3 puntos entiendes mi explicación, te pongo un ejemplo.

Si te pones sobre /tmp y ejecutas pisco create, la straw create se
ejecutará y te preguntará el nombre de la receta por lo tanto creará una
receta con nombre "ejemplo". Al final el resultado será:

/tmp/
/tmp/ejemplo
/tmp/test-results <- creado por el hecho de haber ejecutado un straw en /tmp

no tiene sentido que se genere dentro de /tmp/ejemplo porque es el
resultado de la ejecución de un straw que a priori nunca sabremos lo que va
a hacer.

Lo que propongo es añadir la funcionalidad que haga opcional crear la
carpeta test-results

**Comment by biaggi** [comment]
El problema de esa solución, es que si tengo varias recetas almacenadas en esa carpeta, se van a pisar los archivos, ya que tienen todos el mismo nombre: 

```
jmgomez@jm-kairos:~/cells/cells/cells$ ls test-reports/
pisco-unit.xml
```

Si me aseguras que eso no va a suceder, me parece bien

Saludos

**Comment by sbonacho** [comment]
no entiendo muy bien lo que quieres decir...

¿Te refieres a que si ejecutas varias veces un straw en una misma carpeta
se machaca el directorio test-reports?

Creo que de momento no se ha planteado histórico de ejecuciones a este
nivel, podría plantearse pero de momento el directorio test-reports
corresponde a la última ejecución exclusivamente.

De todas formas tengo la intuición que sigues sin entender lo que te he
comentado antes.. si no, esta cuestión no tendría sentido.

**Comment by biaggi** [comment]
No exactamente, me refiero a que si me creo una carpeta y dentro tengo varios recetas, la carpeta de test va a ser compartida entre todos ellos y por lo tanto va a machacar los cambios.

Corrígeme si me equivoco, si nos remitimos al ejemplo inicial, esto sería un problema:

(1)carpeta raiz donde ejecuto pisco
(2)|-----receta1
(3)|-----receta2
(4)|-----test-reports

Si por lo que creo que dices, esta situación no es posible, entonces habría que meter algún tipo de comprobación para evitar que suceda y/o documentar todas las consideraciones que haya que tener en cuenta para evitar errores humanos y para que todos tengamos claro cual es exactamente la operativa y sepamos a qué atenernos (segunda acepción de la drae ;-) )

En cualquier caso, pienso que la carpeta de test, estaría mejor dentro de la receta, que es lo que intentaba explicar en el issue inicial, ya que pertenecen a la receta y bamboo te permite a nivel de tests seleccionar un filtro que sea pisco-unit.xml que se encuentren en cualquier carpeta. 

Otra posible solución, sería poner un filtro *.xml y en lugar de nombrar todos los tests como pisco-unit,xml se podrían nombrar como pisco-unit-[recpeName].xml para que los nombres no colisionen (donde digo recipeName, quiero decir cualquier cosa que lo haga único por receta)

En general me parecería bien cualquier solución que implique que pueda tener dos recetas en la misma carpeta sin que colisionen sus tests.

Si tengo tiempo luego, te escribo un pull request para que entiendas exactamente cuales son las ventajas de esta pequeña mejora, creo que así no entenderemos mejor.

Saludos

**Comment by sbonacho** [comment]
Trato de explicarte otra vez... creo que no estás entendiendo lo que te
estoy diciendo.

El único objetivo de la carpeta test-reports es almacenar los resultados de
la ejecución de un straw, tiene un significado muy parecido a un log de
ejecución de un comando lo único es que se guarda en una carpeta a parte
por usarlo en bamboo (el nombre de esta carpeta se configura en el
parametro junitDir de piscosour.json). La idea es que en esta carpeta se
almacenen todos los ficheros xml junit generados por una ejecución que
podrán ser varios, por supuesto pero siempre están asociados a una
ejecución.

No tiene ningún significado en el contexto de una receta, es solo el
producto de una ejecución, nada más, no pasa nada porque se machaque por la
siguiente ejecución o se borre si no vamos a hacer nada con este resultado.
Mi propuesta es que por defecto no se genere nunca esta carpeta y que solo
se genere en bamboo o cuando alguien quiera ver el resultado de la
ejecución en formato junit.xml.

El hecho de que casualmente la ejecución de la straw "pisco create" genere
una receta es circunstancial no hay que mezclarlo con el directorio donde
se almacena el resultado de la ejecución de la misma.

Espero que lo tengas más claro...

no es necesario que hagas un PR puesto que estoy trabajando justo ahora
sobre eso... ;)

**Comment by biaggi** [comment]
Lo hablamos en persona, por que todavia no nos hemos entendido

**Comment by sbonacho** [comment]
Cerramos question!
