### ISSUE TITLE
El segundo paso de una straw no se llama

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#34]
Tengo un pipeline con dos tres pasos, de alguna forma, el primer paso que es común para todos los pipelines de este componente, en uno de ellos hace que el siguiente paso no sea llamado.

Ejemplo de código donde sucede con el tag 0.0.17 de piscosour

https://descinet.bbva.es/stash/projects/CELLSLABS/repos/cells-pisco-application-deploy/compare/commits?sourceBranch=refs/heads/feature/step_not_instanciated

**Comment by sbonacho** [comment]
Esto sigue fallando? no encuentro el repositorio.
