### ISSUE TITLE
Desacoplar parámetros de la implementación concreta de lector de parámetros

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#41]
Actualmente se utiliza nopt y su salida se vuelca directamente en shot.runner.params.

Esto nos ata de una forma innecesaria a esta biblioteca. propongo mapear la salida de nopt a otra estructura de datos como por ejemplo algo así [{param1: 'value1', param2: false, param3: true}] ... que nos abstraiga de la implementación de lector de parámetros que la herramienta esté usando.

**Comment by sbonacho** [comment]
Actualmente es así, podemos cambiar nopt cuando queramos, toda la
dependencia a esta librería está en params.js re-implementando esta
librería podríamos usar cualquier otro gestor de parámetros.

De hecho una de las cosas que quería poner en el backlog es la
re-implementación de params.js usando una librería más eficiente.

**Comment by biaggi** [comment]
Obviamente, podemos cambiarla, yo me refiero a si realmente tienen sentido para todos nosotros estos tres arrays:

remain: The remaining args after all the parsing has occurred.
original: The args as they originally appeared.
cooked: The args after flags and shorthands are expanded.

Por que para mi realmente con el cooked, es más que suficiente.

El remain son parámetros que no esperaba recibir y el original es el cooked + remain

**Comment by sbonacho** [comment]
sí, tienes razón, esos arrays no tienen sentido y de hecho no se están
usando por ninguna otra librería, fue una consecuencia de exportar
directamente el objeto que devuelve nopt, para luego usar solo los
parámetros reales...

Completamente de acuerdo en que hay que limpiar la implementación de
params.js.

2016-02-29 12:37 GMT+01:00 Jose Manuel notifications@github.com:

**Comment by sbonacho** [comment]
Se ha refactorizado params.js ahora se exporta un objeto agnóstico a la implementación de la recogida de parámetros de línea de comandos. en #45
