### ISSUE TITLE
Mejoras identificadas

### ISSUE THREAD

**Issue by froucher** [cellsjs/piscosour#5]
Buenas pongo en este hilo el conjunto de mejoras que tenemos localizados para que al menos las tengas registradas:
- Pisco started kit
- Documentación
- Tests 
- Incluir funcionalidad de "npm install" en el core mediante un fichero configuración como el siguiente:

``` json
{
  "workspaceDir" : "workspace",
  "installNpms": [
    {
      "cmd" : "npm",
      "args": ["install","bower"],
      "global" : true,
      "path" : "node_modules/bower/bin/"
    }
  ],
  "installGit": [
    {
      "cmd" : "git",
      "args": ["clone","https://descinet.bbva.es/stash/scm/cel/cells-ci-demo-validation.git"]
    },
    {
      "cmd" : "git",
      "args": ["clone","https://descinet.bbva.es/stash/scm/cel/cells-ci-coverage.git"]
    },
    {
      "cmd" : "git",
      "args": ["clone","https://descinet.bbva.es/stash/scm/cel/cells-ci-lint.git"]
    }
  ]
}
```
- Recetas para acceder a configuración del sistema (por ejemplo si es Mac o Windows....) 
- Recetas para instalar software base (por ejemplo si es necesario phantom, firefox, java, sass, ruby...)
- Documentación contextual de pisco mediante md, no está funcionando, habría que volver a hacerlo funcionar.
- Hacer posible parámetros generales, un parámetro general para todos los parámetros. Por ejemplo workspaceDir en

``` json
{
  "workspaceDir" : "workspace",
  "firefoxMacUrl" : "https://download-installer.cdn.mozilla.net/pub/firefox/releases/44.0/mac/es-ES/Firefox%2044.0.dmg",
  "prompts": [
    {
      "type": "input",
      "name": "repository",
      "required" : true,
      "env" : "bamboo_planRepository_repositoryUrl",
      "message": "Write url fot git repository"
    }
  ]
}
```
- Tiempos de ejecución de cada paso
- Generar logs separados por cada paso
- Generar junit por cada paso de forma genérica. Siempre devolvería un junit.
- Comando "add shot" para que genere un shot nuevo sin tener que hacerlo a mano.
- nopt pueda recibir como parámetro de línea de comando todo lo que lo que cualquier shot tenga en la variable prompt. 

``` json
{
  "workspaceDir" : "workspace",
  "nodeModule" : "cells-deployment-scripts",
  "remoteDir" : "componentsPisco/",
  "prompts": [
    {
      "type": "input",
      "name": "key",
      "required" : true,
      "env" : "bamboo_AWS_KEY",
      "message": "Write aws key for s3"
    },
    {
      "type": "input",
      "name": "password",
      "required" : true,
      "env" : "bamboo_AWS_PASSWORD",
      "message": "Write aws password for s3"
    },
    {
      "type": "input",
      "name": "region",
      "required" : true,
      "env" : "bamboo_AWS_REGION",
      "message": "Write aws region for s3"
    },
    {
      "type": "input",
      "name": "bucket",
      "required" : true,
      "env" : "bamboo_AWS_BUCKET",
      "message": "Write aws bucket for s3"
    },
    {
      "type": "input",
      "name": "urlPrefix",
      "required" : true,
      "env" : "bamboo_CELLS_URL_PREFIX",
      "message": "Write url prefix for cells"
    }
  ]
}
```

**Comment by biaggi** [comment]
Con respecto a: 

nopt pueda recibir como parámetro de línea de comando todo lo que lo que cualquier shot tenga en la variable prompt.

Se podría resolver fácilmente con commander y reflections, solo hay que definir los parámetros adecuadamente

p ej: https://github.com/biaggi/jamonero/blob/master/index.js

```
program
  .version('0.0.1')
  .option('run [task]', 'Run the current pipeline')
  .option("create [type]", "Create a namespace to store tasks")


// take this into consideration to introduce parameters dinamically 
program.option.apply(program, ["test", "desc"]);

program.parse(process.argv);
```

Yo con esto no estoy de acuerdo: "Generar logs separados por cada paso", si ejecutamos cosas de forma asíncrona y cada step tiene su paso puede ser complicado seguir la traza

Y esto no lo entiendo: 

> Incluir funcionalidad de "npm install" en el core mediante un fichero configuración como el siguiente:

Por ejemplo yo estoy usando simplemente el package.json para incluir dependencias.

Qué caso vendría a resolver ese requisito?

**Comment by froucher** [comment]
Otra alternativa con respecto a parámetros por línea de comando es http://vorpal.js.org/
El comportamiento sería muy distinto, es una idea de mejora a trabajar a futuro.

**Comment by biaggi** [comment]
Veo vorpal como helper para el scaffolding, para la línea de comandos no tiene mucho sentido, por que se supone que pisco se va a lanzar en modo desatendido, si en bamboo te falta un parámetro, lo que debería hacer es fallar diciendo lo que te falta, si sale una consola interactiva, simplemente va a ocultar el error de falta de parámetros y probablemente deje el agente tostado durante un tiempo.

**Comment by sbonacho** [comment]
Se han resuelto la mayoría de las mejoras propuestas en este issue. Abro los issues separados de las cosas que faltan.
