### ISSUE TITLE
Añadir un default commando por configuración

### ISSUE THREAD

**Issue by iliasmoreno** [cellsjs/piscosour#53]
Permitir configurar un comando por defecto en caso de que casi siempre se vaya a usar el mismo comando con nuestra receta, o incluso si es la única.

Si no está configurado, al ejecutar nuestra receta (sin parámetros) saldrá la ayuda.
Si está configurado, al ejecutar nuestra receta se ejecutará el parámetro por defecto.

Por ejemplo:
En cells-serve sólo se puede ejecutar **"cells-serve component:serve",** configurando este parámetro, al ejecutar **"cells-serve"** se ejecutaría **"cells-serve component:serve"** en vez de **"cells-serve -h"**.

**Comment by sbonacho** [comment]
Resuelto en #65
