### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#6]
Estaría bien para evitar posibles polémicas que se añadiera un pequeño archivo con la descripción de la nomenclatura que deberían tener las ramas o las reglas que hay que seguir para mandar un PR

**Comment by sbonacho** [comment]
Me puedes echar una mano?, no tengo mucha experiencia con Pull Request ;)

**Comment by biaggi** [comment]
Me senté ayer contigo a explicarte un poco el rollo, no se si esto es anterior o posterior.

Necesitas más ayuda?

**Comment by sbonacho** [comment]
La ayuda que te estoy pidiendo es que añadas el fichero de descripción con
la nomenclatura...etc...  que propones en tu primer issue... no?

2016-02-16 9:42 GMT+01:00 Jose Manuel notifications@github.com:

**Comment by sbonacho** [comment]
Propongo usar commitizen para tratar este problema ;)

https://www.npmjs.com/package/commitizen

**Comment by biaggi** [comment]
Lo hablamos en la próxima planificación a ver si hay alguien que lo quiera hacer, si hay alguien que quiera contribuir se hace, sino, deja de tener sentido
