### ISSUE TITLE
Problemas con Inquirer

### ISSUE THREAD

**Issue by iliasmoreno** [cellsjs/piscosour#73]
Por una parte, en esta línea está dando un error:
[Bug](https://github.com/cellsjs/piscosour/blob/master/plugins/inquirer/plugin.js#L32)
El error se debe a que logger no existe. ¿Debería ser this.logger ahora?

Por otra parte, cuando intento hacer un validation de un campo introducido con inquirer (usando #nombreFuncion), devuelva true o false... sigue adelante, cuando debería volver a preguntar y sacar el mensaje de error.

**Comment by iliasmoreno** [comment]
Olvida la 2ª parte... era cosa mía :P

**Comment by sbonacho** [comment]
fix con #78
